[env:base]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
monitor_speed = 115200

[env:blink]
extends = env:base
build_src_filter = +<scripts/blink.cpp>

[env:test_flex]
extends = env:base
build_src_filter = +<scripts/test_flex.cpp> +<sensors/flex_sensor.h> +<sensors/flex_sensor.cpp>

[env:test_imu]
extends = env:base
build_src_filter = +<scripts/test_imu.cpp> +<sensors/>
lib_deps=
  electroniccats/MPU6050@^1.4.4

[env:test_mqtt]
extends = env:base
build_src_filter = +<scripts/test_mqtt.cpp> +<comms/>
lib_deps =
  knolleary/PubSubClient
  bblanchon/ArduinoJson

[env:test_imu_stream]
extends = env:base
build_src_filter = +<scripts/test_imu_stream.cpp> +<sensors/> +<comms/>
lib_deps =
  electroniccats/MPU6050@^1.4.4
  knolleary/PubSubClient
  bblanchon/ArduinoJson

