[env:dfrobot_firebeetle2_esp32e]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
build_src_filter = +<*> -<scripts/>
lib_deps =
  electroniccats/MPU6050
  eclipse/Paho
  bblanchon/ArduinoJson

[env:blink]
extends = env:dfrobot_firebeetle2_esp32e
build_src_filter = +<scripts/blink.cpp>

[env:test_imu]
extends = env:dfrobot_firebeetle2_esp32e
build_src_filter = +<sensors/*> +<scripts/test_imu.cpp>

[env:test_flex]
extends = env:dfrobot_firebeetle2_esp32e
build_src_filter = +<sensors/*> +<scripts/test_flex.cpp>

[env:test_mqtt]
extends = env:dfrobot_firebeetle2_esp32e
build_src_filter = +<comms/*> +<scripts/test_mqtt.cpp>
