[project]
name = "tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "argparse>=1.4.0",
    "datetime>=6.0",
    "numpy>=2.0.0",
    "paho-mqtt>=2.1.0",
    "scipy>=1.14.0",
    "plotly>=6.0.0",
    "streamlit>=1.40.0",
]
